### ISSUE TITLE
rsyslog 8.15 stops reading journal

### ISSUE THREAD

**Issue by jnovack** [rsyslog/rsyslog-pkg-rhel-centos#22]
rsyslog just plain out stopped reading journalctl.

* Removed rsyslog
* Verified journal
* Cleared /var/lib/rsyslog/
* Reinstalled rsyslog
* used logger
* Proved that it is in journalctl
* Not in /var/log/messages
* Listed /etc/rsyslog.d/* (empty)
* Showed /etc/rsyslog.conf (spoiler alert: it's exactly the same one in the rpm)

I have multiple VMs initially installed with CentOS 7.0, and upgraded throughout time which now experience this issue. This does NOT happen on every VM. This only happens on SOME VMs. Every box is absolutely current with all repos (now CentOS 7.2), I have no rhyme or reason as to why some are failing, and others are fine. I only have VMs, I do not have iron.

Is there ANYTHING I can do to help diagnose this? Is something stuck (statefile?) I'm pulling out my hair here.

```
[root@centos7 ~]# yum erase rsyslog
Loaded plugins: fastestmirror, rhnplugin
This system is receiving updates from RHN Classic or Red Hat Satellite.
Resolving Dependencies
--> Running transaction check
---> Package rsyslog.x86_64 0:8.15.0-1.el7 will be erased
--> Finished Dependency Resolution

Dependencies Resolved

===========================================================================================================================================================
 Package                            Arch                              Version                                    Repository                           Size
===========================================================================================================================================================
Removing:
 rsyslog                            x86_64                            8.15.0-1.el7                               @rsyslog                            2.2 M

Transaction Summary
===========================================================================================================================================================
Remove  1 Package

Installed size: 2.2 M
Is this ok [y/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Erasing    : rsyslog-8.15.0-1.el7.x86_64                                                                                                             1/1
  Verifying  : rsyslog-8.15.0-1.el7.x86_64                                                                                                             1/1

Removed:
  rsyslog.x86_64 0:8.15.0-1.el7

Complete!
[root@centos7 ~]# journalctl --verify
PASS: /run/log/journal/6276c6d480934f1ba6d49fb191f03d2b/system.journal
[root@centos7 ~]# rm -f /var/lib/rsyslog/*
[root@centos7 ~]# yum install rsyslog
Loaded plugins: fastestmirror, rhnplugin
This system is receiving updates from RHN Classic or Red Hat Satellite.
Loading mirror speeds from cached hostfile
 * base: mirror.cogentco.com
 * epel: mirror.symnds.com
 * extras: mirror.symnds.com
 * updates: centos.mirror.nac.net
Resolving Dependencies
--> Running transaction check
---> Package rsyslog.x86_64 0:8.15.0-1.el7 will be installed
--> Finished Dependency Resolution

Dependencies Resolved

===========================================================================================================================================================
 Package                             Arch                               Version                                  Repository                           Size
===========================================================================================================================================================
Installing:
 rsyslog                             x86_64                             8.15.0-1.el7                             rsyslog                             615 k

Transaction Summary
===========================================================================================================================================================
Install  1 Package

Total size: 615 k
Installed size: 2.2 M
Is this ok [y/d/N]: y
Downloading packages:
Running transaction check
Running transaction test
Transaction test succeeded
Running transaction
  Installing : rsyslog-8.15.0-1.el7.x86_64                                                                                                             1/1
  Verifying  : rsyslog-8.15.0-1.el7.x86_64                                                                                                             1/1

Installed:
  rsyslog.x86_64 0:8.15.0-1.el7

Complete!
[root@centos7 ~]# logger Supercalifragilisticexpialidocious
[root@centos7 ~]# journalctl -f | grep Supercalifragilisticexpialidocious
Jan 29 09:42:06 centos7.domain.local root[4326]: Supercalifragilisticexpialidocious
^C
[root@centos7 ~]# tail /var/log/messages
Jan 29 09:13:48 centos7 kernel: [   22.200863] IPVS: Connection hash table configured (size=4096, memory=64Kbytes)
Jan 29 09:13:48 centos7 kernel: [   22.200896] IPVS: Creating netns size=2040 id=0
Jan 29 09:13:48 centos7 kernel: [   22.200936] IPVS: ipvs loaded.
Jan 29 09:18:03 centos7 rsyslogd: [origin software="rsyslogd" swVersion="8.15.0" x-pid="579" x-info="http://www.rsyslog.com"] exiting on signal 15.
Jan 29 09:19:49 centos7 rsyslogd: [origin software="rsyslogd" swVersion="8.15.0" x-pid="2836" x-info="http://www.rsyslog.com"] start
Jan 29 09:28:27 centos7 rsyslogd: [origin software="rsyslogd" swVersion="8.15.0" x-pid="2836" x-info="http://www.rsyslog.com"] exiting on signal 15.
Jan 29 09:28:27 centos7 rsyslogd: [origin software="rsyslogd" swVersion="8.15.0" x-pid="3387" x-info="http://www.rsyslog.com"] start
Jan 29 09:32:20 centos7 rsyslogd: [origin software="rsyslogd" swVersion="8.15.0" x-pid="3387" x-info="http://www.rsyslog.com"] exiting on signal 15.
Jan 29 09:32:20 centos7 rsyslogd: [origin software="rsyslogd" swVersion="8.15.0" x-pid="3649" x-info="http://www.rsyslog.com"] start
Jan 29 09:41:28 centos7 rsyslogd: [origin software="rsyslogd" swVersion="8.15.0" x-pid="3649" x-info="http://www.rsyslog.com"] exiting on signal 15.
[root@centos7 ~]# ls -la /etc/rsyslog.d/
total 12
drwxr-xr-x.  2 root root    6 Dec 18 09:39 .
drwxr-xr-x. 89 root root 8192 Jan 29 09:41 ..
[root@centos7 ~]# cat /etc/rsyslog.conf
# rsyslog configuration file
# note that most of this config file uses old-style format,
# because it is well-known AND quite suitable for simple cases
# like we have with the default config. For more advanced
# things, RainerScript configuration is suggested.

# For more information see /usr/share/doc/rsyslog-*/rsyslog_conf.html
# If you experience problems, see http://www.rsyslog.com/doc/troubleshoot.html

#### MODULES ####

module(load="imuxsock") # provides support for local system logging (e.g. via logger command)
module(load="imklog")   # provides kernel logging support (previously done by rklogd)
#module(load"immark")  # provides --MARK-- message capability

# Provides UDP syslog reception
# for parameters see http://www.rsyslog.com/doc/imudp.html
#module(load="imudp") # needs to be done just once
#input(type="imudp" port="514")

# Provides TCP syslog reception
# for parameters see http://www.rsyslog.com/doc/imtcp.html
#module(load="imtcp") # needs to be done just once
#input(type="imtcp" port="514")


#### GLOBAL DIRECTIVES ####

# Use default timestamp format
$ActionFileDefaultTemplate RSYSLOG_TraditionalFileFormat

# File syncing capability is disabled by default. This feature is usually not required,
# not useful and an extreme performance hit
#$ActionFileEnableSync on

# Include all config files in /etc/rsyslog.d/
$IncludeConfig /etc/rsyslog.d/*.conf


#### RULES ####

# Log all kernel messages to the console.
# Logging much else clutters up the screen.
#kern.*                                                 /dev/console

# Log anything (except mail) of level info or higher.
# Don't log private authentication messages!
*.info;mail.none;authpriv.none;cron.none                /var/log/messages

# The authpriv file has restricted access.
authpriv.*                                              /var/log/secure

# Log all the mail messages in one place.
mail.*                                                  /var/log/maillog


# Log cron stuff
cron.*                                                  /var/log/cron

# Everybody gets emergency messages
*.emerg                                                 :omusrmsg:*

# Save news errors of level crit and higher in a special file.
uucp,news.crit                                          /var/log/spooler

# Save boot messages also to boot.log
local7.*                                                /var/log/boot.log


# ### begin forwarding rule ###
# The statement between the begin ... end define a SINGLE forwarding
# rule. They belong together, do NOT split them. If you create multiple
# forwarding rules, duplicate the whole block!
# Remote Logging (we use TCP for reliable delivery)
#
# An on-disk queue is created for this action. If the remote host is
# down, messages are spooled to disk and sent when it is up again.
#$WorkDirectory /var/lib/rsyslog # where to place spool files
#$ActionQueueFileName fwdRule1 # unique name prefix for spool files
#$ActionQueueMaxDiskSpace 1g   # 1gb space limit (use as much as possible)
#$ActionQueueSaveOnShutdown on # save messages to disk on shutdown
#$ActionQueueType LinkedList   # run asynchronously
#$ActionResumeRetryCount -1    # infinite retries if host is down
# remote host is: name/ip:port, e.g. 192.168.0.1:514, port optional
#*.* @@remote-host:514
# ### end of the forwarding rule ###
[root@centos7 ~]# cat /etc/systemd/journald.conf
#  This file is part of systemd.
#
#  systemd is free software; you can redistribute it and/or modify it
#  under the terms of the GNU Lesser General Public License as published by
#  the Free Software Foundation; either version 2.1 of the License, or
#  (at your option) any later version.
#
# Entries in this file show the compile time defaults.
# You can change settings by editing this file.
# Defaults can be restored by simply deleting this file.
#
# See journald.conf(5) for details.

[Journal]
#Storage=auto
#Compress=yes
#Seal=yes
#SplitMode=uid
#SyncIntervalSec=5m
#RateLimitInterval=30s
#RateLimitBurst=1000
#SystemMaxUse=
#SystemKeepFree=
#SystemMaxFileSize=
#RuntimeMaxUse=
#RuntimeKeepFree=
#RuntimeMaxFileSize=
#MaxRetentionSec=
#MaxFileSec=1month
#ForwardToSyslog=no
#ForwardToKMsg=no
#ForwardToConsole=no
#ForwardToWall=yes
#TTYPath=/dev/console
#MaxLevelStore=debug
#MaxLevelSyslog=debug
#MaxLevelKMsg=notice
#MaxLevelConsole=info
#MaxLevelWall=emerg
```

I originally had a red herring with the omelasticsearch module in this [issue](https://github.com/rsyslog/rsyslog/issues/698), which may, at second glance be the same problem. Perhaps the issue started in 8.14?

**Comment by jnovack** [comment]
Considering they are all VMs and I'm not sure the reason they are failing.  Is it POSSIBLE we are running into [this redhat acknowledged bug](https://bugzilla.redhat.com/show_bug.cgi?id=1088021)?

**Comment by portante** [comment]
If you load `imjournal` I think it will start working.  Did you try that?

**Comment by davidelang** [comment]
On Fri, 29 Jan 2016, Peter Portante wrote:

> If you load `imjournal` I think it will start working.  Did you try that?

The comments in the bug identify this as a problem in systemd, so I would not 
expect that imjournal would help.

It sounds as if journald is getting confused when time goes backwards and in 
trying to avoid outputting an infinate loop of messages (which they have done 
before), they are stopping output.

I would guess that when the real time gets past the point where the time was set 
backwards, things will start working again.

so if you set the time back 10 min, will you start seeing data after another 10 
min? (not all the logs, but at least new ones after that point)

I've posted to the bugzilla entry to ask about this

David Lang

**Comment by portante** [comment]
@davidelang I only ask because the bug shows an `rsyslog.conf` file that uses `imjournal`, and last I checked, this problem has been reported with an `rsyslog.conf` file that does not use `imjournal`, and while the posted `journald.conf` shows `ForwardToSyslog=no`.  So I am not sure how rsyslog gets data from `systemd`.

**Comment by davidelang** [comment]
ahh, I missed the first post on the topic here, I just saw the last two and went 
to the bugzilla where they identify this as a journald issue.

**Comment by jnovack** [comment]
If this was one machine, doing it once, I would absolutely agree with you.  However:

* This is occurring on multiple (virtual) machines on multiple (hosts)
* This issue persists even when I "stop/start" or "restart" rsyslog.
* This issue persists even when I "stop/start" or "restart" journald.
* This issue persists even when I delete, vacuum, or clear the journal.
* Not EVERY machine has this problem.

I'm under the impression that I should be using `imjournal` [only if there is hard need to do so.](http://www.rsyslog.com/doc/v8-stable/configuration/modules/imjournal.html)

**Comment by portante** [comment]
@jnovack, it is unclear to me why the Adiscon repo builds rsyslog for EL systems different than what Fedora, CentOS, and RHEL provide.  Fedora, CentOS, and RHEL have been using imjournal for quite some time.  So I am don't think there is a problem with using it.  It is the case that upstream rsyslog does not support it, but yet it includes it in the provided source code, which also can be confusing.

What I am not sure about still in your configuration is how rsyslog is getting events from systemd based on the configurations provided.  If we can determine how that works, we might be able to figure out what is happening.  But with out `imjournal`, I am just not sure.

Can you perhaps check to see if systemd is configured to listen on by checking the contents of `/usr/lib/systemd/system/systemd-journald.socket`?

**Comment by jnovack** [comment]
> The key point to understand is imjournal is not necessary to be run on a system, because the journal forwards all syslog data, more or less unmodified to the syslog daemon. 
> -- Rainer Gerhards, https://youtu.be/GTS7EuSdFKE?t=7m51s

I was going by this, to assume that I did not (and do not) need `imjournal` to receive my logs (such as `logger hello`).

It's pulled out from the `rsyslog.conf` within the adiscon RPM for a reason.  Why?   Is the intent of 8.x RPMs to eliminate `/var/log/messages` and such by forcing(?) you to use the journal?  This way, the use of `imjournal` is optional?

If it is, then it's entirely my misunderstanding, and this is a mute issue.  I guess I am under the impression that it's supposed to be working WITHOUT `imjournal` given all the warnings and quotes, it's conflicting information, I'm just looking for the truth.

`/usr/lib/systemd/system/systemd-journald` is an executable, the `systemd-journald.socket` systemd file listens on `/run/systemd/journal/stdout`, `/run/systemd/journal/socket` and `/dev/log`.

**Comment by davidelang** [comment]
rsyslog can work without imjournal under two conditions.

1. you configure systemd to not take over /dev/log so that rsyslog can use it as it did pre-systemd

  In this scenario, applications write logs to /dev/log, rsyslog reads and parses them.

2. you configure systemd to forward logs to rsyslog

  In this scenario, applications write logs to /dev/log, journald reads them, parses them, reassembles something almost identical to what the applications sent in the first place[1], sends them to rsyslog, rsyslog then reads and parses them. Optionally, journald will fetch metadata from the system, then make system calls to forge the metadata when it send the log to rsyslog.

If neither of these are the case, then you have to have the systemd journal receive the logs, parse them, write them to temporary storage, then have rsyslog periodically query journald to find out if it has any new logs, and if so, fetch them from temporary storage, format them, and pass them to rsyslog that then needs to parse them again.

Can you understand why the rsyslog developers think that this third option should not be the default?

[1] no, the systemd journal doesn't just pass what it received, there are conditions (https://github.com/rsyslog/rsyslog-pkg-rhel-centos/issues/22#issuecomment-177036266) sends something different than what it receives, because the developers believe that what the application sent was so wrong that it would be unethical to forward it with whitespace intact.

**Comment by portante** [comment]
Reading this, http://www.freedesktop.org/software/systemd/man/journald.conf.html#Forwarding%20to%20traditional%20syslog%20daemons, it would seem that the `imjournal` method is the best because all the boot log messages can be read in and processed by rsyslog.

For Fedora, CentOS, and RHEL, the distribution provided `rsyslog.conf` files seem to rely on this behavior to get boot messages in `/var/log/boot.log` and in `/var/log/messages`.  

It would seem that systemd metadata is lost when forwarding to messages from systemd to rsyslog because it is not providing that metadata over the socket that rsyslog reads from with `imuxsock`.  That seems to be why Fedora, CentOS, and RHEL all use `imjournal` as well.

We happen to be relying on `imjournal` for our "common logging" efforts in order to leverage the very useful metadata provided by systemd with the logs.

I plan on doing some performance analysis of `imjournal` and the message transfers to see where the limits and bottlenecks are.

**Comment by jnovack** [comment]
I just did a `ForwardToSyslog=yes` option, and I'm honestly in no position to say whether I got all the messages from `/var/log/boot` or not.  But the Kernel messages do start at `[0.00000000]`.

**Comment by davidelang** [comment]
rsyslog never had a problem reading and reporting the boot messages before systemd came along

the metadata is lost because systemd inserts itself in the stream. rsyslog can retrieve the metadata itself if the application is logging directly to rsyslog ( module(load="imuxsock" SysSock.Annotate="on" SysSock.ParseTrusted="on") ). Systemd can be set to forge at least some of the metadata, but it's expensive to do so.

So if you accept that all logs must first go to systemd (which I don't), and that it's too expensive/bothersome for systemd to forge the metadata (which I do agree with), and that you will actually use the metadata (which I do on my systems, but question how common it is), then imjournal becomes the only thing that will work.

I would really like to see measurements of the following options

1. delivering directly to rsyslog, minimal config without metadata
2. delivering directly to rsyslog, minimal config with metadata
3. delivering to journald, forwarded to rsyslog without metadata
4. delivering to journald, forwarding to rsyslog with forged metadata
5. delivering to journald, storing in /tmp (ramdisk), retrieved by imjournal
6. delivering to journald, storing on a real filesystem, retrieved by imjournal

The difficulty is going to be in how to measure the costs across the different components involved, some of which are fairly easy to measure, some of which are not.

I see us needing to measure:

- simple write to /dev/log (logger)
- rsyslog time/cycles to read the log, add it to a queue, read it from the queue, write to file (simplest halfway real config)
- syscall time/cycles to retrieve metadata
- journald time to retrieve/parse/forward log
- syscall time/cycles to forge metadata
- journald time to retrieve/parse/store log in memory
- journald time to retrive log from memory and deliver to imjournal request (imjournal time is measurable as part of rsyslog time)
- kernel time for filesystem IOps if journal writes to a filesystem (and making sure that this isn't shortcut by memory caching)

for programs that we can start/stop at will, we can measure them via time (and mitigate startup/shutdown costs by seeing how the time scales with more messages). Watch out for any fsync's happening at shutdown that would not happen if things kept running, they would make disk I/O look like program time.

but with journald I don't know that we can do that, and for kernel accounting, I know we can't.

Is there some way to do this with perf?

**Comment by davidelang** [comment]
@jnovack if the first few messages gives the kernel version and command line, you have everything.

FYI, one of the reasons you see people hostile to (or at least very cynical of) systemd is that systemd has spread a lot of FUD, claiming that they made things possible that weren't possible before when they had been around for years. There were a few things had been under discussion but not implemented yet (metadata gathering, options to make output files tamper resistant), but were implemented at least as well as journald did within a very short time of it's release, but are still listed as if they are only available in journald.

the unwillingness to work with others as you see in https://github.com/systemd/systemd/issues/98#issuecomment-110917254 and https://github.com/systemd/systemd/issues/959 doesn't help.

This whole topic of how to get the logs to rsyslog is a perfect example, as this was being proposed, their mantra was "you won't have to change your existing logging at all, journald will be transparent and deliver everything", but as soon as they were a mandatory part of the distro it changed to "our way or the highway", and when they had bugs in their code and data files that cause anything reading those files per the spec to go into an endless loop, they were blaming the thing reading it (rsyslog imjournal) when their own journalctl would run into the identical problem. Things were broken for months with them pointing fingers and imjournal, showing that they treated the logs as write-only items in practice.

**Comment by jnovack** [comment]
At this point, we've deviated enough from my original issue (which was a NON-issue).  So I'm going to close this and tag it with #PEBKAC and #Trump2016 (to troll).

I appreciate you both showing me the light, I just wish it was a little more obvious from the get-go.

Thank you again.

**Comment by davidelang** [comment]
fair enough, but if anyone does set anything up to do benchmarks of the options, please share them widely and invite others to run the same tests (and examine them, suggest improvements, etc). We have really needed this for a while, but I haven't had the circular 2it yet :-)

**Comment by jnovack** [comment]
I'm a little green (obviously from this thread) on the interactions here, could you provide example config options (just the highlights) for each of the 6 tests?

**Comment by davidelang** [comment]
I can help with the rsyslog side, but not really on the journald side. I can also help with test harness stuff, but initially I would try to just do shell scripts around logger. We aren't after X messages/sec, we are after X cycles/message type info. Almost the inverse of it, but not quite.

for the rsyslog side, there are two basic modes, reading from /dev/log and reading from imjournal

for tests 1,3
http://www.rsyslog.com/doc/v8-stable/configuration/modules/imuxsock.html

global(  net.enableDNS = "off")
module(load="imuxsock" SysSock.RateLimit.Interval="0")
/var/log/test

for tests 2,4

global(  net.enableDNS = "off")
module(load="imuxsock" SysSock.RateLimit.Interval="0" SysSock.Annotate="on" SysSock.ParseTrusted="on")
/var/log/test

for tests 5,6
http://www.rsyslog.com/doc/v8-stable/configuration/modules/imjournal.html

global(  net.enableDNS = "off")
module(load="imjournal" PersistStateInterval="100" StateFile="/path/to/file" ratelimit.interval="0")
/var/log/test

for tests 5,6 we may need to do the following instead
global(  net.enableDNS = "off")
module(load="imjournal" PersistStateInterval="100" StateFile="/path/to/file" ratelimit.interval="0")
module(load="mmjsonparse")
action(type="mmjsonparse")
/var/log/test

We may need to use a different template than the default one to show all the metadata we are collecting.

And there are some tunables (queue sizes, batch size) that could affect things a bit, but I think getting baseline measurements first without trying to do serious performance tweaks is the best thing to do. The only 'performance' stuff I've done in these configs (other than leaving things out) is to disable ratelimits that would artificially slow us down or throw away logs, and turn off DNS lookups (which should all be for 127.0.0.1)

If someone could throw together a patch for journald that sent the metadata as JSON in the body of the message, then we would have a test 7, which would look like test #1 except with mmjsonparse added on the rsyslog side and the formatting on the journald side. I think that would be by far the best option.

note that the very latest version of rsyslog supports using libfastjson instead of json-c, there is a huge performance difference between them when dealing with anything beyond the basic variables (metadata, or parsing JSON)

**Comment by aturetta** [comment]
I understand the issue is closed, but in fact I have several Centos 7 VMs where, after upgrading the native rsyslog with 8.16, I cannot see logs from sshd, policyd, etc... any more.

I really think the default config from the project repos should bring the system to the same functionality than the native repo.
Is the solution loading imjournal, imuxsock, or what?

**Comment by davidelang** [comment]
remember that the distros create and alter their configs on their own. We (the rsyslog project) don't always know what they have done, or why. We welcome patches to our build process to make things better align with the distros.

That said, there is a bit of a disconnect/disagreement when it comes to interacting with the journal (as noted above)

We don't really trust imjournal, because it's so dependent on the internal data in the binary journal files, and we've already been burned at least once by that data being corrupt but rsyslog getting blamed for the resulting infinite loop.

If we can setup the performance tests mentioned above so that we can talk about the actual costs of the different options, then I think we would be in far better shape to discuss changing defaults with distros.

**Comment by portante** [comment]
FWIW, I have a setup that I have started down that path.

The first step I have done is numbers of journald itself in various configurations.  I hope to post the driver script for that first and the configuration in a github project this week or next.
