### ISSUE TITLE
systemd Alias / syslog.service symlink missing in RPM

### ISSUE THREAD

**Issue by nyetsche** [rsyslog/rsyslog-pkg-rhel-centos#44]
Hello,

I'm trying to reconcile this repo and the associated RPMs with what's in the source code.

In the EL7 specfile, the `Alias=syslog.service` is commented out: `;Alias=syslog.service`

https://github.com/rsyslog/rsyslog-pkg-rhel-centos/blob/master/rpmbuild/SPECS/v8-stable-el7.spec#L484

The original source code is not: https://github.com/rsyslog/rsyslog/blob/master/rsyslog.service.in#L15

There's a long thread at https://github.com/rsyslog/rsyslog/issues/2134 that involves *not* commenting out this line (therefore creating the symlink). That is also what's described in http://www.rsyslog.com/rsyslog-8-32-0-v8-stable-released/ .

So ... should this line be commented in the most recent RPMs?

**Comment by deoren** [comment]
> @nyetsche: So ... should this line be commented in the most recent RPMs?

I can't speak for the state of the files in this repo (I too was confused when I looked recently, but I think it is because a series of patches are applied on top of some base files), but I think the intent is to match the existing configuration for CentOS/RHEL 7 systems in regards to imjournal and imuxsock integration:

1. Use imjournal for the "feed" of messages from systemd
1. Do not listen on `/dev/log` or `/run/systemd/journal/syslog` via imuxsock.

For my own use, I've chosen to override that behavior, first with drop-ins and later with a full override in `/etc/systemd/system/rsyslog.service` to restore the desired behavior: use imuxsock to listen on the `/run/systemd/journal/syslog` socket like Ubuntu 16.04 systems do by default. If you're interested, I can share that file. If not (and you are specifically looking to reconcile the repo sources with the package only), not a problem, just thought I'd offer.

**Comment by nyetsche** [comment]
Actually, that makes perfect sense. The default `rsyslog.conf` file includes `$ModLoad imjournal`.

But, current documentation - https://www.rsyslog.com/doc/v8-stable/configuration/modules/imjournal.html - says:

> imjournal may simply be replaced by imuxsock, and we highly suggest doing so.

and

> It is strongly recommended to use this plugin only if there is hard need to do so.

Making me wonder why it should be the default.

**Comment by nyetsche** [comment]
@deoren if you could share your `rsyslog.conf` for Ubuntu 16.04/`imuxsock` I think it'd be helpful for the community at large.

**Comment by deoren** [comment]
@nyetsche Will try to respond in more detail later, but see also rsyslog/rsyslog-doc#503.

**Comment by deoren** [comment]
Real quick, here is the file that I'm currently using:

https://github.com/deoren/rsyslog-examples/blob/master/etc/systemd/system/rsyslog.service
