### ISSUE TITLE
About ipv6

### ISSUE THREAD

**Issue by opfanswyx** [rsyslog/rsyslog-pkg-rhel-centos#53]
How to configure IPv6 in rsyslog. conf? Can we judge the success of sending IPv6 information locally by tpdump?

**Comment by rgerhards** [comment]
there is no special option needed. If you have dual stack - or only ipv6 - it's active :-)

**Comment by opfanswyx** [comment]
Excuse me, I have two questions to ask you.
1. Can the ipv6 function be used normally on a 32-bit system?
2. I don't currently have an ipv6 environment. I tried to use tcpdump to capture packets on the local device to verify the ipv6 functionality of rsyslog. I configured an ipv6 address in the rsyslog.conf that does not exist in the remote end, but I can't catch any information related to ipv6. Is this normal?

**Comment by rgerhards** [comment]
> * Can the ipv6 function be used normally on a 32-bit system?

Nothing special - IPv6 is fully supported for over 10 yrs.

> * I don't currently have an ipv6 environment. I tried to use tcpdump to capture packets on the local device to verify the ipv6 functionality of rsyslog. I configured an ipv6 address in the rsyslog.conf that does not exist in the remote end, but I can't catch any information related to ipv6. Is this normal?

For a good answer, I would post this to a Linux networking forum.

**Comment by rgerhards** [comment]
> > * I don't currently have an ipv6 environment. I tried to use tcpdump to capture packets on the local device to verify the ipv6 functionality of rsyslog. I configured an ipv6 address in the rsyslog.conf that does not exist in the remote end, but I can't catch any information related to ipv6. Is this normal?
> 
> For a good answer, I would post this to a Linux networking forum.

what I mean is: I am not 100% sure if the IP stack sends out something if you want to connect to an non-existing IPv6 address. Probably an ARP request. Well, should send the packet if you address it to a non-local IPv6 address AND if you have configured the IPv6 gateway. You see, all networking questions. 

You don't need rsyslog to check this. You can just use `netcat` (`nc`).

It's good that you move to IPv6 and I understand you have questions. But these are better targeted towards a networking forum because they are the same for all software. While I also have a network engineer education, it's long since I actively maintained networks - plus my time is limited. Again: great to see you finally move towards IPv6!

**Comment by opfanswyx** [comment]
打扰了，非常感谢您
Excuse me. Thank you very much.
